### ISSUE TITLE
Explain why branded types replaces newtype

### ISSUE THREAD

**Issue by steida** [gcanti/newtype-ts#23]
As I understand, branded type replaces newtype, except in the case where we explicitly don't want downgradeability to the base type, which is very rare (string token to not be considered to be string for security purposes).

https://github.com/gcanti/io-ts-types/issues/111

**Comment by steida** [comment]
I believe this awesome lib should be deprecated or io-ts should be mentioned at least. 

@gcanti I can send PR.

**Comment by gcanti** [comment]
> I believe this awesome lib should be deprecated

Some people prefer newtypes over branded types

See also https://github.com/gcanti/io-ts-types/issues/111
