### ISSUE TITLE
iso returns any with last typescript

### ISSUE THREAD

**Issue by Spaubleit** [gcanti/newtype-ts#25]
Hello. Just tried this library first time. I got any after iso function call with typescript 4.2.3.

Here is codesandbox with example:
https://codesandbox.io/s/any-iso-return-type-k09r6?file=/src/index.ts

**Comment by gcanti** [comment]
@Spaubleit I can't repro, did you add `fp-ts`, `monocle-ts` as dependencies? The link you provided says:

```
DependencyNotFoundError
Could not find dependency: 'fp-ts' relative to '/node_modules/newtype-ts/es6/index.js'
```

**Comment by Spaubleit** [comment]
Sorry. I feel stupid now  :)
